### ISSUE TITLE
Compile fail at 100% on Ubuntu MATE

### ISSUE THREAD

**Issue by marcuschildress** [Aloshi/EmulationStation#528]
Compiler fails at 100%
Ubuntu MATE 15.10
Pretty OS fresh install - one week ago

Am I missing development libraries? 

[ 96%] Building CXX object es-app/CMakeFiles/emulationstation.dir/src/views/gamelist/DetailedGameListView.cpp.o
[ 97%] Building CXX object es-app/CMakeFiles/emulationstation.dir/src/views/gamelist/IGameListView.cpp.o
[ 98%] Building CXX object es-app/CMakeFiles/emulationstation.dir/src/views/gamelist/ISimpleGameListView.cpp.o
[ 99%] Building CXX object es-app/CMakeFiles/emulationstation.dir/src/views/gamelist/GridGameListView.cpp.o
[100%] Building CXX object es-app/CMakeFiles/emulationstation.dir/src/views/SystemView.cpp.o
[100%] Building CXX object es-app/CMakeFiles/emulationstation.dir/src/views/ViewController.cpp.o
Linking CXX executable ../emulationstation
CMakeFiles/emulationstation.dir/src/GamelistDB.cpp.o: In function `populate_recursive(boost::filesystem::path const&, std::vector<std::string, std::allocator<std::string> > const&, boost::filesystem::path const&, SystemData const*, sqlite3*, sqlite3_stmt*)':
GamelistDB.cpp:(.text+0x1530): undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
GamelistDB.cpp:(.text+0x156c): undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
GamelistDB.cpp:(.text+0x159a): undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
CMakeFiles/emulationstation.dir/src/main.cpp.o: In function `main':
main.cpp:(.text.startup+0x30): undefined reference to `boost::locale::generator::generate(std::string const&) const'
../libes-core.a(ThemeData.cpp.o): In function `ThemeData::getThemeSets()':
ThemeData.cpp:(.text+0x6ae): undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
ThemeData.cpp:(.text+0x6d6): undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
collect2: error: ld returned 1 exit status
es-app/CMakeFiles/emulationstation.dir/build.make:872: recipe for target 'emulationstation' failed
make[2]: *** [emulationstation] Error 1
CMakeFiles/Makefile2:301: recipe for target 'es-app/CMakeFiles/emulationstation.dir/all' failed
make[1]: *** [es-app/CMakeFiles/emulationstation.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2
marc@Pi:~/EmulationStation$

**Comment by marcuschildress** [comment]
Resolved. 

sudo apt-get libboost-all-dev

**Comment by tnotm** [comment]
I am getting this exact error.  I ran ```sudo apt-get install libboost-all-dev``` but the error is still occurring.

**Comment by elleuc4** [comment]
Hello, I'm having this issue too. Surely installing all dev libraries won't help. The error message is very clear. Did anyone manage to solve this?

**Comment by marcuschildress** [comment]
I backed out of Ubuntu Mate and went with Raspbian. Sucks though, liked Ubuntu personally. Nice interface, even if a small performance penalty. 

Marc
